version: '2.1'

services:
  
  backend-service:
    image: nagabhushanamn/backend-service
    ports:
      - 8181:8080
    
  frontend-service:
    image: nagabhushanamn/frontend-service
    ports:
      - 81:80
     
     
        