pipeline {
    agent any
     environment { 
        registry = "nagabhushanamn/backend-service" 
        registryCredential = 'dockerhub' 
        dockerImage = '' 
    }
    stages {
        stage('checkout from scm') {
            steps {
                echo 'checkout..'
            }
        }
        stage('compile') {
            steps {
                dir("backend-service"){
                    sh 'mvn clean compile'
                }
            }
        }
        stage('unit-test') {
            steps {
                dir("backend-service"){
                    sh 'mvn test'
                }
            }
        }
        stage('integration-testing') {
            steps {
                dir("backend-service"){
                    sh 'mvn test'
                }
            }
        }
        stage('package') {
            steps {
                dir("backend-service"){
                    sh 'mvn package'
                }
            }
        }
        // stage('QA') {
        //     steps {
        //         dir("backend-service"){
        //             input "Ready to deploy?"
        //         }
        //     }
        // }
    }  
}