pipeline {
    agent any
     environment { 
        registry = "nagabhushanamn/backend-service" 
        registryCredential = 'dockerhub' 
        dockerImage = '' 
    }
    stages {
        stage('checkout from scm') {
            steps {
                echo 'checkout..'
            }
        }
        stage('compile') {
            steps {
                dir("backend-service"){
                    sh 'mvn clean compile'
                }
            }
        }
        stage('unit-test') {
            steps {
                dir("backend-service"){
                    sh 'mvn test'
                }
            }
        }
        stage('integration-testing') {
            steps {
                dir("backend-service"){
                    sh 'mvn test'
                }
            }
        }
        stage('package') {
            steps {
                dir("backend-service"){
                    sh 'mvn package'
                }
            }
        }
        stage('docker:build') {
            steps {
                dir("backend-service"){
                    script { 
                        dockerImage = docker.build registry + ":latest" 
                    }
                }
            }
        }
        stage('docker:push') {
            steps {
                script { 
                    docker.withRegistry('', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        }
        stage('Cleaning up') { 
            steps { 
                sh "docker rmi $registry:latest"
            }
        } 
    }
    
       
    }  
}