pipeline {
    agent any
     environment { 
        registry = "nagabhushanamn/frontend-service" 
        registryCredential = 'dockerhub' 
        dockerImage = '' 
    }
    stages {
        stage('checkout from scm') {
            steps {
                echo 'checkout..'
            }
        }
        stage('test') {
            steps {
            }
        }
        stage('build') {
            steps {
                dir("frontend-service"){
                    sh 'npm i'
                    sh 'npm run build'
                }
            }
        }
        
    }
}