pipeline {
    agent any
     environment { 
        registry = "nagabhushanamn/frontend-service" 
        registryCredential = 'dockerhub' 
        dockerImage = '' 
    }
    stages {
        stage('checkout from scm') {
            steps {
                echo 'checkout..'
            }
        }
        stage('build') {
            steps {
                dir("frontend-service"){
                    sh 'npm i'
                    sh 'npm run build'
                }
            }
        }
        stage('docker:build') {
            steps {
                dir("frontend-service"){
                    script { 
                        dockerImage = docker.build registry + ":$BUILD_NUMBER" 
                    }
                }
            }
        }
        stage('docker:push') {
            steps {
                script { 
                    docker.withRegistry('', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        }
        stage('Cleaning up') { 
            steps { 
                sh "docker rmi $registry:$BUILD_NUMBER" 
            }
        } 
    }
}